### ISSUE TITLE
Create Wordpress acount

### ISSUE THREAD

**Issue by leikkisa** [team-josie/learning#1]
## Background
Wordpress is a popular free platform for making websites and blogs. It is customizable and there are a lot of freelance jobs to do Wordpress development, theming, and customization.

For this project, we'll create a Wordpress site as a place to first blog about our learning activities. This will help develop the practice of writing, documentation, and potentially sharing. It will be useful in the future as a reminder of what we've done and learned.

It will also be available for us to play with to get familiar with the Wordpress platform.

## Acceptance criteria
- [x] Choose a name for your URL - it will look like chosenname.wordpress.com
- [x] Sign up for a free Wordpress account at http://www.wordpress.com
- [x] Log in and navigate to "Posts", create a new post describing what you just did, especially if there was anything tricky about it
- [x] Publish your post
- [x] Pin WordPress in your browser

## Notes
The post you create doesn't have to be long or anything fancy.  Over time this will be sort of like a notebook.

**Comment by kaengri** [comment]
Done the thing I have.
